# -*- coding: utf-8 -*-
"""CSV_Merger.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15Kiz3aT9UsNHu3V-bX6zKDx1HPBT66xC
"""

import pandas as pd
import os
from google.colab import drive, auth
import gspread
import google.auth
import numpy as np

# mount the root folder of Google Drive
drive.mount('/content/drive', force_remount=True)

# get the path of the folder that contains the csv files
folder = '/content/drive/MyDrive/Metadata_Files'

# get the list of csv file names in the folder
files = [f for f in os.listdir(folder) if f.endswith('.csv')]

# create an empty dataframe to store the concatenated data
df = pd.DataFrame()

# loop over the file names
for file in files:
    # read the csv file with the selected columns
    data = pd.read_csv(os.path.join(folder, file), usecols=['CollectionName', 'CollectionDescription', 'LeadPoC', 'LeadPoCEmail', 'StudyType', 'Discipline', 'DataCustodian',	'DataCustodianEmail',	'OwnerPrincipal',	'Consortium',	'Organism',	'CollectionId',	'PublishId',	'DatasetName',	'Study',	'AssayType',	'DatasetVersion',	'DatasetId',	'WorkingGroup',	'InstrumentCode',	'SampleName',	'DataProcessingLevel',	'MaterialCode',	'ReplicateNumber', 'ExperimentID', 'StudyID',	'file_id',	'DataFormat',	'PrincipleContactID',	'ProtocolID',	'SiteCode',	'ExperimentType',	'id',	'labcasId',	'name',	'labcasName',	'FileType',	'FileSize',	'FileDownloadId',	'FileId',	'DateMod',	'ICmd5sum',	'labcas_node_type',	'FileName',	'FileVersion',	'FileLocation',	'RealFileLocation',	'_version_'])
    # add a new column with the file name as the label
    data['label'] = file[:-4] # remove the .csv extension
    # concat the data to the dataframe
    df = pd.concat([df, data], ignore_index=True)

# replace the invalid float values with zero
df = df.fillna(0)

# authenticate the Colab notebook with Google account
auth.authenticate_user()
# get the credentials
scope = ['https://spreadsheets.google.com/feeds', 'https://www.googleapis.com/auth/drive']
creds, project = google.auth.default(scopes=scope)
# create a gspread client
gc = gspread.authorize(creds)

# open the Google sheet by its key
wb = gc.open_by_key('19dXXXbmNxnN7oyenNe56kwgTR_ix6Q9gHB2UN11vXhs')
# create a new worksheet
ws = wb.add_worksheet(title='Metadata_C', rows=10000, cols=50)
# append the dataframe to the worksheet
ws.append_rows(df.values.tolist())